%% MexMaker
mex -v CXXFLAGS='$CXXFLAGS --std=c++17 -fno-omit-frame-pointer'...
    ThreeTubeMex/WithStabilityComp/ThreeTubeMexWithStabilityComp.cpp ...
    ReferenceCannulaKinematics/Rk8_Coeffs.cpp...
    ReferenceCannulaKinematics/TaggedInterval.cpp...
    -I./ReferenceCannulaKinematics...
    -I/Users/jessedalmeida/CppLibraries/include/Eigen...
    -I/Users/jessedalmeida/CppLibraries/include/boost
