mex -v CXXFLAGS='$CXXFLAGS --std=c++17 -fno-omit-frame-pointer'...
    FourTubeMex/FourTubeMex.cpp ...
    ReferenceCannulaKinematics/Rk8_Coeffs.cpp...
    ReferenceCannulaKinematics/TaggedInterval.cpp...
    -I./ReferenceCannulaKinematicsAtS...
    -I/Users/jessedalmeida/CppLibraries/include/Eigen...
    -I/Users/jessedalmeida/CppLibraries/include/boost
