mex -v CXXFLAGS='$CXXFLAGS -std=c++11 -fno-omit-frame-pointer' ThreeTubeMex.cpp...
    ../ReferenceCannulaKinematics/Rk8_Coeffs.cpp...
    ../ReferenceCannulaKinematics/TaggedInterval.cpp...
    -I../ReferenceCannulaKinematics...
    -I"C:/Libraries/include"...
    -I"C:/Libraries/include/Eigen"
